# yaml files path
yaml_section_path: "./yamls/"

# yaml files
yaml_section_files: 
  # <file name> : <name>, if name is empty use file name without extension
  - "section-general.yaml" : general
  - "section-training_logger.yaml" : training_logger
  
  - "section-aggregation.yaml": aggregation
  - "section-client_selection.yaml": client_selection
  - "section-dataset_loader.yaml" : dataset_loader
  - "section-data_distribution.yaml" : distribution
  - "section-loss_func.yaml" : loss_func
  - "section-lora.yaml" : lora
  - "section-nn_model.yaml" : nn_model
  - "section-fl_nodes.yaml" : fl_nodes
  - "section-optimizer.yaml" : optimizer
  - "section-training.yaml" : training
  - "section-client_strategy.yaml" : client_strategy
  - "section-server_strategy.yaml" : server_strategy
  - "section-runner_strategy.yaml" : runner_strategy
  - "section-trainer.yaml" : trainer
#---------------------------------------
# Combine yamls, can define any combination name,
# such as 'runner', 'runner-test', 'runner-a' etc
#---------------------------------------
yaml_combination:
  # Runner
  runner: [general, training_logger, fl_nodes, runner_strategy]

  # Client
  client_yaml: [general, training_logger, dataset_loader, nn_model, loss_func, optimizer, training, distribution, client_strategy, trainer] #, trainer

  # Edge
  edge_yaml: []  

  # Server
  # server_yaml: [general, training_logger, dataset_loader, nn_model, aggregation, client_selection, server_strategy, trainer]
  server_yaml: [general, training_logger, dataset_loader, nn_model, loss_func, optimizer, training, distribution, client_strategy, trainer, client_selection, server_strategy, aggregation]

  # Other combinations
